# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  fitNet_ci:
    jobs:
      - build-test-lint
      - deploy:
          requires:
            - build-test-lint
          filters:
            branches:
              only: Production

jobs:
  build-test-lint:
    executor: node/default
    steps:
      - checkout
      - run:
          name: install app dependencies
          command: npm install
      - run:
          name: run tests
          command: npm run test
      - run:
          name: run linter
          command: npm run lint

  deploy:
    executor: node/default
    steps:
      - checkout
      - run:
          name: deploy to render
          command: curl "https://api.render.com/deploy/srv-cqc37tjv2p9s73fg1hl0?key=JiC9HIVqvwM"
